
base_url = 'https://reqres.in/api'
users_url = f'{base_url}/users'
update_url = f'{base_url}/users/2'
list_users = f'{base_url}/users?page=2'
login_url = f'{base_url}/login'
delayed_url = f'{base_url}/users?delay=3'
register_url = f'{base_url}/register'
not_found_url = f'{base_url}/unknown/23'
login_successful = f'{base_url}/login'
register_successful = f'{base_url}/api/register'
not_found = f'{base_url}/unknown/23'